### ISSUE TITLE
Add opt-in ping groups

### ISSUE THREAD

**Issue by Furbeh** [PJB3005/MoMMI#2]
Add the ability for the bot to manage ping groups so people can more easily organize things such as videogames.
For example:
@MoMMI addmeto Vidyagame would add me to a ping list named Vidyagame
@MoMMI removeme Vidyagame would remove me from the ping list
@MoMMI ping Vidyagame would ping either in chat or in PMs the people in Vidyagame

While not necessary it probably would be a good idea to have a command that lists the ping lists
@MoMMI pinglists would PM a list of currently existing lists (potentially with how many people are in them?)

**Comment by DrCelt** [comment]
working on it

**Comment by Exxion** [comment]
GitHub user MoMMI must be very confused about all these pings

**Comment by Furbeh** [comment]
>\>it's been 19 days

**Comment by DrCelt** [comment]
I have no idea how to code this and my attempts were lacklustre at best.

**Comment by PJB3005** [comment]
Right, this is done now.
