### ISSUE TITLE
Empty changelogs are commited

### ISSUE THREAD

**Issue by Visne** [PJB3005/MoMMI#47]
![image](https://user-images.githubusercontent.com/39844191/141791923-6d9d9c57-e86f-46c2-8ff1-cfce45936542.png)

leads to

![image](https://user-images.githubusercontent.com/39844191/141791979-d1373e3c-0983-4402-b75b-2d0105325b9a.png)

**Comment by PJB3005** [comment]
Wrong repo, MoMMI literally does nothing for SS14 changelogs. You want https://github.com/space-wizards/SS14.Changelog instead.
